// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3FsIFqHEYLhv5Sa0YG6OjfnoETk3kkMc',
    appId: '1:206492858709:web:b0e24d870dc888818a17dc',
    messagingSenderId: '206492858709',
    projectId: 'warnakita-db',
    authDomain: 'warnakita-db.firebaseapp.com',
    databaseURL: 'https://warnakita-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'warnakita-db.appspot.com',
    measurementId: 'G-JJS0TJR00Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB36werj8MF95kvBID2sXvWa7kl6gQtlVs',
    appId: '1:206492858709:android:f2746bd18c1623e98a17dc',
    messagingSenderId: '206492858709',
    projectId: 'warnakita-db',
    databaseURL: 'https://warnakita-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'warnakita-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTp7nftJJ5zxNCVJIbP_IJfe61nLTkwr8',
    appId: '1:206492858709:ios:879423a54d7d34158a17dc',
    messagingSenderId: '206492858709',
    projectId: 'warnakita-db',
    databaseURL: 'https://warnakita-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'warnakita-db.appspot.com',
    iosClientId: '206492858709-sfqemc89tuvahp1dmapud2jakj7p6mni.apps.googleusercontent.com',
    iosBundleId: 'com.example.warnakita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTp7nftJJ5zxNCVJIbP_IJfe61nLTkwr8',
    appId: '1:206492858709:ios:879423a54d7d34158a17dc',
    messagingSenderId: '206492858709',
    projectId: 'warnakita-db',
    databaseURL: 'https://warnakita-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'warnakita-db.appspot.com',
    iosClientId: '206492858709-sfqemc89tuvahp1dmapud2jakj7p6mni.apps.googleusercontent.com',
    iosBundleId: 'com.example.warnakita',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3FsIFqHEYLhv5Sa0YG6OjfnoETk3kkMc',
    appId: '1:206492858709:web:782f322f65ab75698a17dc',
    messagingSenderId: '206492858709',
    projectId: 'warnakita-db',
    authDomain: 'warnakita-db.firebaseapp.com',
    databaseURL: 'https://warnakita-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'warnakita-db.appspot.com',
    measurementId: 'G-ZS7XZPGH14',
  );

}